# Generated by Django 5.1.6 on 2025-02-21 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdetection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverbehavior',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='detected_object',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='fine_amount',
        ),
        migrations.AddField(
            model_name='detectedobject',
            name='new_field',
            field=models.CharField(default='DefaultValue', max_length=100),
        ),
        migrations.AddField(
            model_name='driverbehavior',
            name='detected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverbehavior',
            name='location',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverbehavior',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='detected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='violations/'),
        ),
        migrations.AddField(
            model_name='violation',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='violation',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='object_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driverbehavior',
            name='behavior_type',
            field=models.CharField(choices=[('reckless', 'Reckless Driving'), ('drunk', 'Drunk Driving'), ('distracted', 'Distracted Driving'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('speeding', 'Speeding'), ('signal_jump', 'Signal Jump'), ('wrong_lane', 'Wrong Lane'), ('other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='TrafficAuthority',
        ),
    ]
